all:
	gcc -c binary_search_tree.c; gcc -c -I ./ usage_binary_search_tree.c; gcc -o demo_binary_search_tree binary_search_tree.o usage_binary_search_tree.o

clean:
	rm binary_search_tree.o; rm usage_binary_search_tree.o; rm demo_binary_tree;